[project]
name = "fundrating"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "alpha-vantage>=3.0.0",
    "bt>=1.1.0",
    "fastexcel>=0.14.0",
    "ipykernel>=6.29.5",
    "ipywidgets>=8.1.5",
    "lmo>=0.14.2",
    "openpyxl>=3.1.5",
    "pandas>=2.2.3",
    "pyarrow>=18.1.0",
    "toolkitvdw",
    "tqdm>=4.67.1",
    "yfinance>=0.2.50",
]

[tool.uv.sources]
toolkitvdw = { path = "toolkitvdw" }
